### ISSUE TITLE
http://localhost:8080/Popoji/login 404 - not found

### ISSUE THREAD

**Issue by meigiyanto** [PopojiCMS/Popoji#28]
Saya coba install popoji di localhost menggunakan composer bawaan aplikasi ksweb di smartphone dengan spesifikasi composer saya atur ke PHP versi 7.2 dan web servernya menggunakan lighttpd.Setelah selesai instalasi dan sukses kemudian saya coba akses ke http://localhost:8080/Popoji/login tapi malah muncul "404 - not found".

Dari halaman http://localhost:8080/Popoji saya coba view-source:http://localhost:8080/popoji memang di tag yang mengarah ke halaman login sudah sama yaitu http://localhost:8080/Popoji/login.Setelah saya coba masukkan RewriteBase / di .htaccess juga tidak ada perubahan.

**Comment by DwiraSurvivor** [comment]
Untuk web server lighttpd, silahkan konfigurasi lighttpd.conf seperti ini :

$HTTP["host"] =~ "example.com$" {
        server.document-root = "/path/to/our/public/"
        accesslog.filename = "/path/to/access.log"

        alias.url = ()
        url.redirect = ()
        url.rewrite-once = (
                "^/(css|img|js|fonts)/.*\.(jpg|jpeg|gif|png|swf|avi|mpg|mpeg|mp3|flv|ico|css|js|woff|ttf)$" => "$0",
                "^/(favicon\.ico|robots\.txt|sitemap\.xml)$" => "$0",
                "^/[^\?]*(\?.*)?$" => "index.php/$1"
        )
}
