### ISSUE TITLE
Illuminate\Database\QueryException SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) (SQL: select * from `settings` where `options` = member_registration limit 1

### ISSUE THREAD

**Issue by cakmoel** [PopojiCMS/Popoji#33]
I tried Popoji version 3.0.0, installed it on local host successfully. after installation I went to my browser and visit the front-page and login page. I faced the same problem on both page with this error 
`Illuminate\Database\QueryException
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) (SQL: select * from `settings` where `options` = member_registration limit 1)`
![Screenshot from 2021-04-16 21-20-48](https://user-images.githubusercontent.com/414011/115030928-34378b00-9efa-11eb-9857-2bc87a52ce3f.png)

I checked the database password again and again, it was correct. So, What would you guys doing to fix this error and unexpected ?.

**Comment by DwiraSurvivor** [comment]
Please check po-includes/.env file and change with your correct DB connection 

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=popoji
DB_USERNAME=root
DB_PASSWORD=

**Comment by cakmoel** [comment]
i had checked it. my database password was correct. i wrote it with letters, number and some symbols, but it did not work in popoji at all.

**Comment by gibrandev** [comment]
@cakmoel If you use letters, number and some symbols use "" 
example 
`DB_PASSWORD="pass.word %%%"`
