### ISSUE TITLE
Kalo error begini kenapa?

### ISSUE THREAD

**Issue by ifsya** [PopojiCMS/Popoji#34]
C:\xampp\htdocs\popoji\po-includes\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php on line 500

**Comment by DwiraSurvivor** [comment]
Versi php-nya berapa yng dipakai ?

**Comment by ifsya** [comment]
ini kak, PHP 5.6.40 (VC11 X86 32bit thread safe) + PEAR

**Comment by DwiraSurvivor** [comment]
Popoji Versi 3 hanya support PHP versi 7.2 > ke atas

**Comment by ifsya** [comment]
baik, terimakasih..
