### ISSUE TITLE
missing files ?

### ISSUE THREAD

**Issue by RoyalC** [PopojiCMS/Popoji#8]
hello i install it well but when i'm want to access the site it's make this error:

Warning: require(C:\laragon\www/po-includes/vendor/autoload.php): failed to open stream: No such file or directory in C:\laragon\www\index.php on line 32

Fatal error: require(): Failed opening required 'C:\laragon\www/po-includes/vendor/autoload.php' (include_path='.;C:/laragon/etc/php/pear') in C:\laragon\www\index.php on line 32

i'm using laragon

thanks

**Comment by DwiraSurvivor** [comment]
You can open terminal, and goto po-includes folder and then you can run this command : composer install
